### ISSUE TITLE
Does not compile, as is

### ISSUE THREAD

**Issue by Peter0x44** [DS-Homebrew/10SecondRun-DS#1]
In order to compile this homebrew, I had to first add `#include <cstddef>` to arm9/include/graphics/gif.hpp
Afterwards, it couldn't find a linker script, `ds_arm9_hi.specs`
I copied it from here: https://github.com/devkitPro/devkitarm-crtls/blob/master/ds_arm9.specs and placed it in arm9/
Then, it complained patch_ndsheader-dsiware.py was missing, which I copied from here:
https://github.com/DS-Homebrew/TWiLightMenu/blob/master/patch_ndsheader_dsiware.py

Could the repo be fixed, so compiling doesn't require these steps?

**Comment by Epicpkmn11** [comment]
Can also just remove [gif.hpp:63](https://github.com/DS-Homebrew/10SecondRun-DS/blob/main/arm9/include/graphics/gif.hpp#L63), not sure why that line suddenly started causing issues (it broke in hiya too), but it's completely unused. Could also change the specs to `-specs=ds_arm9.specs` to use the default, but not sure if it needs the modified one.
